seeds: 10

# number of folds to split the data into
folds: 10

# RandomSeed
random_seed: 0

# Implemented: "single_tasks", "fusion", "ensemble"
mode: "single_tasks"

# Implemented: "gnb", "lr", "rf", "dummy"
classifiers: [ "lr", "rf" ]

# Implemented: "cookie_theft", "pupil_calib", "memory", "reading"
tasks: [ "Memory", "PupilCalib", "CookieTheft", "Reading" ]

# output folder: specify which folder you'd like the results to go to (will be sent under ../results/)
output_folder: "dummy_result1"

# any conditions on PID list extraction
# options can be "default",
PID_extraction_method: "default"

# eye tracking calibration flag for participant log
# 1: Keep all data
# 2: Only reject participants for whom calibration failed
# 3: Reject all participants for whom calibration was not perfect
eye_tracking_calibration_flag : 2

# REDCap API Key to be specified here
redcap_api_key: "A15772EE1FDA385ABB4C0353B21D7B8D"
